# Generated by Django 3.1.1 on 2020-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcblog', '0007_auto_20200918_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above To Read Blog Post...', max_length=255),
        ),
    ]
